lib/wo_web/router.ex
defmodule WoWeb.Router do
  use WoWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :authorized do
    plug WoWeb.Plug.Authorize
  end

  scope "/", WoWeb do
    pipe_through :browser

    get "/login", SessionController, :new
    post "/login", SessionController, :create
    delete "/logout", SessionController, :delete
  end

  scope "/", WoWeb.Visitor do
    pipe_through :browser # Use the default browser stack

    get "/", HomeController, :index

    get "/series", SermonSeriesController, :index
    get "/series/:slug", SermonSeriesController, :show

    get "/sermon/:slug", SermonController, :show

    get "/search", SearchController, :index

    get "/newsletter", NewsletterController, :signup

    get "/register", VisitorController, :new
    post "/register", VisitorController, :create

    get "/cart", CartController, :show
    delete "/cart", CartController, :delete

    post "/cart_item", CartItemController, :create
    delete "/cart_item", CartItemController, :delete
    put "/cart_item", CartItemController, :update
  end

  scope "/admin", WoWeb.Admin, as: :admin do
    pipe_through [:browser, :authorized]

    resources "/sermon_series", SermonSeriesController, except: [:show] do
      resources "/sermon", SermonController
    end
  end
end

lib/wo_web/views/layout_view.ex
defmodule WoWeb.LayoutView do
  use WoWeb, :view

  def flash_callout_tag(_, nil), do: ""
  def flash_callout_tag(:info, value), do: content_tag(:p, value, class: "callout primary")
  def flash_callout_tag(:warn, value), do: content_tag(:p, value, class: "callout warning")
  def flash_callout_tag(:error, value), do: content_tag(:p, value, class: "callout alert")
  def flash_callout_tag(conn) do
    Enum.reduce([:info, :warn, :error], [], fn(key, acc) -> acc ++ [flash_callout_tag(key, get_flash(conn, key))] end)
  end

  def nav_link(conn, text, path, opts \\ []) do
    class = if conn.request_path == path, do: "active", else: ""
    content_tag(:li, link(text, Keyword.merge([to: path], opts)), class: class)
  end
end

lib/wo_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><%= assigns[:page_title] || "Wisdom for the Heart" %></title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">

    <script type="text/javascript" src="https://sdk.amazonaws.com/js/aws-sdk-2.21.0.min.js"></script>
    <script type="text/javascript" src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script src="https://s3.amazonaws.com/wisdomonline-development/jwplayer.js"></script>
    <script>jwplayer.key="<%= System.get_env("WFTH_PERMISSIONS_JWPLAYER_LICENSE_KEY") %>";</script>
  </head>

  <body>
    <div class="top-bar">
      <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
          <%= nav_link @conn, "WFTH", home_path(@conn, :index) %>
          <%= if user(@conn) && user(@conn).administrator do %>
            <%= nav_link @conn, "Admin", admin_sermon_series_path(@conn, :index) %>
          <% end %>
          <%= nav_link @conn, "Sermon Series", sermon_series_path(@conn, :index) %>
          <%= nav_link @conn, "News", newsletter_path(@conn, :signup) %>
          <%= nav_link @conn, "Cart", cart_path(@conn, :show) %>
          <%= if logged_in?(@conn) do %>
            <%= nav_link @conn, "Logout", session_path(@conn, :delete), method: :delete %>
          <% else %>
            <%= nav_link @conn, "Log in", session_path(@conn, :new) %>
          <% end %>
        </ul>
      </div>

      <%= form_for @conn, search_path(@conn, :index), [method: :get, enforce_utf8: false, as: :search, class: "top-bar-right"], fn f -> %>
        <ul class="menu">
          <li><%= text_input f, :q, name: "q", type: "search", placeholder: "Search sermons & series" %></li>
          <li><button type="submit" class="button">Search</button></li>
        </ul>
      <% end %>
    </div>

    <%= flash_callout_tag(@conn) %>

    <div class="row">
      <div class="large-12 columns">
        <%= render @view_module, @view_template, assigns %>
      </div>
    </div>

    <script>
      $(document).foundation();
    </script>
  </body>
</html>